### PR TITLE
fix: news from multiple handles

### LINKED ISSUE #3: Make news source configurable via start request
Right now news source is not configurable and developer needs to modify that by updating the code by themselves. Idea is to add news source in start script so user can add multiple news handles which they want their agent to fetch news from.

### PR DESCRIPTION
**Pull request by 0xtarunkm**
fixes #3

### CODE REVIEW

File: src/workers/tweetWorker.ts [hunk 1]
```diff
@@ -31,29 +32,54 @@ export const generateAndTweet = async (prompt: string, newsPrompt: string) => {
...
+          });
+          return tweets?.data?.data[0]?.text;
+        } catch (error) {
+          console.error(`Error fetching tweets from ${handle}:`, error);
+          return null;
+        }
+      };
+
+      let newsContent: string | null = null;
+      for (const handle of handles) {
```
Comment (CodingTux) [inline src/workers/tweetWorker.ts:60]: let's select one randomly? otherwise it will mostly fetch tweets from 1st handle itself

Comment (CodingTux) [reply src/workers/tweetWorker.ts:60]: or shuffle, whatever is best

Comment (0xtarunkm) [reply src/workers/tweetWorker.ts:60]: shuffle sounds good

**Review by CodingTux — APPROVED** [review]
